-- outcome_data 新增 TP/SL 擴充欄位（idempotent）
-- TP targets
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_plus250_time  TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_plus300_time  TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_plus400_time  TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_plus500_time  TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp250_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp250_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp300_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp300_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp400_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp400_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp500_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS tp500_within_10m  BOOLEAN DEFAULT FALSE;
-- SL levels 擴充
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_minus125_time TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_minus150_time TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_minus200_time TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_minus250_time TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS first_minus300_time TIME;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl125_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl125_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl150_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl150_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl200_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl200_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl250_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl250_within_10m  BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl300_within_5m   BOOLEAN DEFAULT FALSE;
ALTER TABLE outcome_data ADD COLUMN IF NOT EXISTS sl300_within_10m  BOOLEAN DEFAULT FALSE;
